image: debian:stable

variables:
  ANDROID_COMPILE_SDK: "34"
  ANDROID_SDK_TOOLS: "11076708"
  ANDROID_BUILD_TOOLS: "34.0.0"

include:
  - template: Code-Quality.gitlab-ci.yml

stages:
  - build
  - test

build:
  stage: build
  tags:
    - docker
  before_script:
    - apt-get --quiet update --yes
    - apt-get --quiet install default-jre --yes
    - apt-get --quiet install default-jdk --yes
    - apt-get --quiet install --yes wget tar unzip lib32stdc++6 lib32z1

    # Setup path as ANDROID_SDK_ROOT for moving/exporting the downloaded sdk into it
    - export ANDROID_SDK_ROOT="${PWD}/android-home"
    # Create a new directory at specified location
    - install -d $ANDROID_SDK_ROOT
    # Here we are installing androidSDK tools from official source,
    # (the key thing here is the url from where you are downloading these sdk tool for command line, so please do note this url pattern there and here as well)
    # after that unzipping those tools and
    # then running a series of SDK manager commands to install necessary android SDK packages that'll allow the app to build
    - wget --output-document=$ANDROID_SDK_ROOT/cmdline-tools.zip https://dl.google.com/android/repository/commandlinetools-linux-${ANDROID_SDK_TOOLS}_latest.zip
    # move to the archive at ANDROID_SDK_ROOT
    - pushd $ANDROID_SDK_ROOT
    - unzip -d cmdline-tools cmdline-tools.zip
    - pushd cmdline-tools
    - mv cmdline-tools tools || true
    - popd
    - popd
    - export PATH=$PATH:${ANDROID_SDK_ROOT}/cmdline-tools/tools/bin/

    # Nothing fancy here, just checking sdkManager version
    - sdkmanager --version

    # use yes to accept all licenses
    - yes | sdkmanager --licenses || true
    - sdkmanager "platforms;android-${ANDROID_COMPILE_SDK}"
    - sdkmanager "platform-tools"
    - sdkmanager "build-tools;${ANDROID_BUILD_TOOLS}"

    # VERY necessary
    - chmod +x ./gradlew
  script:
    - ./gradlew assembleRelease # command to build
  only:
    - main #set trigger for CICD if push or merge in master branch
  artifacts:
    paths:
      - ./app/build/outputs/ # set artifact path which store your APK file

code_quality:
  image: docker:19.03.11
  tags:
    - docker-build
  variables:
    SOURCE_CODE: "/app/src/main/java/**"
  artifacts:
    reports:
      codequality: gl-code-quality-report.json
    paths:
      - gl-code-quality-report.json