image: mreichelt/android:34

stages:
  - build

build:
  stage: build
  tags:
    - docker
  script:
    - ./gradlew assembleDebug # command to build and debug
  only:
    - main #set trigger for CICD if push or merge in master branch
  artifacts:
    paths:
      - ./app/build/outputs/ # set artifact path which store your APK file