stages:
  - build
  - test

include:
  - template: Code-Quality.gitlab-ci.yml

build_android:
  image: debian:stable

  stage: build

  tags:
    - docker

  variables:
    ANDROID_COMPILE_SDK: "34"
    ANDROID_SDK_TOOLS: "11076708"
    ANDROID_BUILD_TOOLS: "34.0.0"
    SECURE_FILES_DOWNLOAD_PATH: './'
  
  script:
    - chmod +x ci/android-build-env.sh
    - .ci/android-build-env.sh 

  #only:
  #  - main # main branch trigger

  artifacts:
    paths:
      - ./build/outputs/android/

build_arduino:
  image: debian:stable

  stage: build

  tags:
    - docker-build
  
  script:
    - chmod +x ci/arduino-build-env.sh
    - .ci/arduino-build-env.sh 

  #only:
  #  - main # main branch trigger

  artifacts:
    paths:
      - ./build/outputs/arduino/

code_quality:
  image: docker:19.03.11

  tags:
    - docker-build

  variables:
    SOURCE_CODE: "/app/src/main/java/**"

  artifacts:
    reports:
      codequality: gl-code-quality-report.json

    paths:
      - gl-code-quality-report.json