stages:
  - build
  - test

include:
  - template: Code-Quality.gitlab-ci.yml
  - template: Security/SAST.gitlab-ci.yml

build_android:
  image: debian:stable

  stage: build

  tags:
    - docker

  variables:
    ANDROID_COMPILE_SDK: "34"
    ANDROID_SDK_TOOLS: "11076708"
    ANDROID_BUILD_TOOLS: "34.0.0"
    SECURE_FILES_DOWNLOAD_PATH: './'
  
  before_script:
    - cd ci
    - chmod +x android-build-env.sh
    - ./android-build-env.sh 
    - cd ..

  script: 
    - export ANDROID_SDK_ROOT="${PWD}/android-home"
    - export PATH=$PATH:${ANDROID_SDK_ROOT}/cmdline-tools/tools/bin/
    - chmod +x ./gradlew
    - ./gradlew assembleRelease

  only:
    - main # main branch trigger

  artifacts:
    paths:
      - ./app/build/outputs/

build_arduino:
  image: debian:stable

  stage: build

  tags:
    - docker-build
  
  before_script:
    - cd ci
    - chmod +x arduino-build-env.sh
    - ./arduino-build-env.sh 
    - cd ..

  script:
    - export PATH=$PATH:${PWD}/bin
    - cd terminal
    - arduino-cli compile --fqbn Seeeduino:samd:seeed_wio_terminal --output-dir ./build/output

  only:
    - main # main branch trigger

  artifacts:
    paths:
      - ./terminal/build/output

code_quality:
  image: docker:19.03.11

  tags:
    - docker-build

  variables:
    SOURCE_CODE: "/**"

  artifacts:
    reports:
      codequality: gl-code-quality-report.json

    paths:
      - gl-code-quality-report.json

sast:
  tags:
    - docker-build
  only:
    - merge_requests