stages:
  - build
  - test

include:
  - template: Code-Quality.gitlab-ci.yml

variables: 
  SECURE_FILES_DOWNLOAD_PATH: './'

build_android:
  image: debian:stable

  stage: build

  tags:
    - docker

  variables:
    ANDROID_COMPILE_SDK: "34"
    ANDROID_SDK_TOOLS: "11076708"
    ANDROID_BUILD_TOOLS: "34.0.0"
  
  before_script:
    - chmod +x android-build-env.sh
    - ./android-build-env.sh 

  script:
    - chmod +x ./gradlew
    - ./gradlew assembleRelease

  #only:
  #  - main # main branch trigger

  artifacts:
    paths:
      - ./build/outputs/android/

build_arduino:
  image: debian:stable

  stage: build

  tags:
    - docker-build
  
  before_script:
    - chmod +x arduino-build-env.sh
    - ./arduino-build-env.sh 
    
  script:
    - arduino-cli compile --fqbn Seeeduino:samd:seeed_wio_terminal

  #only:
  #  - main # main branch trigger

  artifacts:
    paths:
      - ./build/outputs/arduino/

code_quality_android:
  image: docker:19.03.11

  tags:
    - docker

  variables:
    SOURCE_CODE: "/app/src/main/java/**"

  artifacts:
    reports:
      codequality: code-quality-android.json

    paths:
      - code-quality-android.json

code_quality_arduino:
  image: docker:19.03.11

  tags:
    - docker-build

  variables:
    SOURCE_CODE: "/terminal/**"

  artifacts:
    reports:
      codequality: code-quality-arduino.json

    paths:
      - code-quality-arduino.json