#include "ConnectivityIcons.h"
#include <TFT_eSPI.h>
#include "UIMacros.h"


void drawWiFiConnectionIcon(TFT_eSPI tft, bool wifiDeviceConnected){
  // empty the region for new icon
  tft.drawRect(WIFI_ICON_CIRCLE_X - WIFI_ICON_CIRCLE_MAX_RAD, WIFI_ICON_CIRCLE_Y - WIFI_ICON_CIRCLE_MAX_RAD, WIFI_ICON_CIRCLE_MAX_RAD * 2, WIFI_ICON_CIRCLE_MAX_RAD * 2, DEFAULT_BG_COLOR);

  // draw 3 circles
  for(int i = 0; i < 3; i++){
    tft.drawCircle(WIFI_ICON_CIRCLE_X, WIFI_ICON_CIRCLE_Y, WIFI_ICON_CIRCLE_MAX_RAD - WIFI_ICON_CIRCLE_RADIUS_DIFF * i, wifiDeviceConnected == CONNECTED ? WIFI_ICON_ICON_COLOR_ON : WIFI_ICON_ICON_COLOR_OFF);
  }

  // use 2 triangles to mask the 3 circles into 3 arcs
  tft.fillTriangle(WIFI_ICON_CIRCLE_X - WIFI_ICON_CIRCLE_MAX_RAD, WIFI_ICON_CIRCLE_Y + WIFI_ICON_CIRCLE_MAX_RAD, WIFI_ICON_CIRCLE_X + WIFI_ICON_CIRCLE_MAX_RAD, WIFI_ICON_CIRCLE_Y - WIFI_ICON_CIRCLE_MAX_RAD, WIFI_ICON_CIRCLE_X + WIFI_ICON_CIRCLE_MAX_RAD, WIFI_ICON_CIRCLE_Y + WIFI_ICON_CIRCLE_MAX_RAD, DEFAULT_BG_COLOR);
  tft.fillTriangle(WIFI_ICON_CIRCLE_X + WIFI_ICON_CIRCLE_MAX_RAD, WIFI_ICON_CIRCLE_Y + WIFI_ICON_CIRCLE_MAX_RAD, WIFI_ICON_CIRCLE_X - WIFI_ICON_CIRCLE_MAX_RAD, WIFI_ICON_CIRCLE_Y - WIFI_ICON_CIRCLE_MAX_RAD, WIFI_ICON_CIRCLE_X - WIFI_ICON_CIRCLE_MAX_RAD, WIFI_ICON_CIRCLE_Y + WIFI_ICON_CIRCLE_MAX_RAD, DEFAULT_BG_COLOR);
}

void drawBltConnectionIcon(TFT_eSPI tft, bool bleDeviceConnected){
  // decide the color according to connection status
  uint32_t color;
  if(bleDeviceConnected){
    color = BLT_ICON_COLOR_ON;
  }else{
    color = BLT_ICON_COLOR_OFF;
  }

  // empty the region for new icon
  tft.drawRect(BLT_ICON_START_X, BLT_ICON_START_Y, BLT_ICON_WIDTH, BLT_ICON_HEIGHT, DEFAULT_BG_COLOR);

  // draw the bluetooth icon
  tft.drawLine(BLT_ICON_START_X, BLT_ICON_START_Y + BLT_ICON_HEIGHT * 3/4, BLT_ICON_START_X + BLT_ICON_WIDTH, BLT_ICON_START_Y + BLT_ICON_HEIGHT * 1/4, color);
  tft.drawLine(BLT_ICON_START_X + BLT_ICON_WIDTH, BLT_ICON_START_Y + BLT_ICON_HEIGHT * 1/4, BLT_ICON_START_X + BLT_ICON_WIDTH * 1/2, BLT_ICON_START_Y, color);
  tft.drawLine(BLT_ICON_START_X + BLT_ICON_WIDTH * 1/2, BLT_ICON_START_Y, BLT_ICON_START_X + BLT_ICON_WIDTH * 1/2, BLT_ICON_START_Y + BLT_ICON_HEIGHT, color);
  tft.drawLine(BLT_ICON_START_X + BLT_ICON_WIDTH * 1/2, BLT_ICON_START_Y + BLT_ICON_HEIGHT, BLT_ICON_START_X + BLT_ICON_WIDTH, BLT_ICON_START_Y + BLT_ICON_HEIGHT * 3/4, color);
  tft.drawLine(BLT_ICON_START_X + BLT_ICON_WIDTH, BLT_ICON_START_Y + BLT_ICON_HEIGHT * 3/4, BLT_ICON_START_X, BLT_ICON_START_Y + BLT_ICON_HEIGHT * 1/4, color);
}